# Generated by Django 3.0.4 on 2021-06-28 23:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='栽培エリア')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(verbose_name='X座標')),
                ('y', models.IntegerField(verbose_name='Y座標')),
                ('w', models.IntegerField(verbose_name='幅')),
                ('h', models.IntegerField(verbose_name='高さ')),
            ],
        ),
        migrations.CreateModel(
            name='CropManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='実施日')),
            ],
        ),
        migrations.CreateModel(
            name='MagementGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='管理グループ')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='野菜')),
            ],
        ),
        migrations.CreateModel(
            name='Varietie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='品種')),
                ('vegetable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mvg.Vegetable', verbose_name='野菜')),
            ],
        ),
        migrations.CreateModel(
            name='GrowingCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeding_date', models.DateTimeField(verbose_name='種まき日')),
                ('planting_date', models.DateTimeField(verbose_name='植付日')),
                ('transplanting_date', models.DateTimeField(verbose_name='移植日')),
                ('harvest_date_start', models.DateTimeField(verbose_name='収穫開始日')),
                ('harvest_date_end', models.DateTimeField(verbose_name='収穫完了日')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvg.Area', verbose_name='栽培エリア')),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvg.Coordinate', verbose_name='座標')),
                ('management_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvg.CropManagement', verbose_name='管理グループ')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvg.Varietie', verbose_name='品種')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='畑')),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvg.Coordinate', verbose_name='座標')),
            ],
        ),
        migrations.AddField(
            model_name='cropmanagement',
            name='management_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvg.MagementGroup', verbose_name='管理グループ'),
        ),
        migrations.AddField(
            model_name='area',
            name='coordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvg.Coordinate', verbose_name='座標'),
        ),
        migrations.AddField(
            model_name='area',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvg.Field', verbose_name='畑'),
        ),
    ]
