# Generated by Django 3.0.4 on 2021-06-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MagementGroup',
            new_name='ManagementGroup',
        ),
    ]
