# Generated by Django 3.0.4 on 2021-06-29 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvg', '0002_auto_20210629_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growingcrop',
            name='harvest_date_end',
            field=models.DateTimeField(null=True, verbose_name='収穫完了日'),
        ),
        migrations.AlterField(
            model_name='growingcrop',
            name='harvest_date_start',
            field=models.DateTimeField(null=True, verbose_name='収穫開始日'),
        ),
        migrations.AlterField(
            model_name='growingcrop',
            name='management_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvg.ManagementGroup', verbose_name='管理グループ'),
        ),
        migrations.AlterField(
            model_name='growingcrop',
            name='planting_date',
            field=models.DateTimeField(null=True, verbose_name='植付日'),
        ),
        migrations.AlterField(
            model_name='growingcrop',
            name='seeding_date',
            field=models.DateTimeField(null=True, verbose_name='種まき日'),
        ),
        migrations.AlterField(
            model_name='growingcrop',
            name='transplanting_date',
            field=models.DateTimeField(null=True, verbose_name='移植日'),
        ),
    ]
