# Generated by Django 3.0.4 on 2021-07-05 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvg', '0006_auto_20210704_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growingcrop',
            name='harvest_date_end',
        ),
        migrations.RemoveField(
            model_name='growingcrop',
            name='harvest_date_start',
        ),
        migrations.RemoveField(
            model_name='growingcrop',
            name='planting_date',
        ),
        migrations.RemoveField(
            model_name='growingcrop',
            name='seeding_date',
        ),
        migrations.RemoveField(
            model_name='growingcrop',
            name='transplanting_date',
        ),
        migrations.AlterField(
            model_name='growingcrop',
            name='coordinate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mvg.Coordinate', verbose_name='座標'),
        ),
    ]
