# Generated by Django 3.0.4 on 2021-07-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvg', '0007_auto_20210705_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='growingcrop',
            name='harvest_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='収穫完了日'),
        ),
        migrations.AddField(
            model_name='growingcrop',
            name='harvest_date_start',
            field=models.DateField(blank=True, null=True, verbose_name='収穫開始日'),
        ),
        migrations.AddField(
            model_name='growingcrop',
            name='planting_date',
            field=models.DateField(blank=True, null=True, verbose_name='植付日'),
        ),
        migrations.AddField(
            model_name='growingcrop',
            name='seeding_date',
            field=models.DateField(blank=True, null=True, verbose_name='種まき日'),
        ),
        migrations.AddField(
            model_name='growingcrop',
            name='transplanting_date',
            field=models.DateField(blank=True, null=True, verbose_name='移植日'),
        ),
        migrations.AlterField(
            model_name='cropmanagement',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='実施日'),
        ),
    ]
